### ISSUE TITLE
Installation documentation error: No Module found: frictionless

### ISSUE THREAD

**Issue by jwdebelius** [qiime2/q2-fmt#31]
**Bug Description**
I installed q2-fmt into a clean qiime2-2022.2 environment on my M1 Mac per the instruction on github page.

When I try to run any commands with q2-fmt, or now when I initalize my qiime2 enviroment, I get an error message:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/util.py", line 224, in get_plugin_manager
    return qiime2.sdk.PluginManager.reuse_existing()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 58, in reuse_existing
    raise UninitializedPluginManagerError
qiime2.sdk.plugin_manager.UninitializedPluginManagerError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 781, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/click/command.py", line 43, in parse_args
    return super().parse_args(ctx, args)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 1209, in parse_args
    echo(ctx.get_help(), color=ctx.color)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 570, in get_help
    return self.command.get_help(self)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 975, in get_help
    self.format_help(ctx, formatter)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/click/core.py", line 1003, in format_help
    self.format_options(ctx, formatter)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/click/command.py", line 157, in format_options
    for subcommand in self.list_commands(ctx):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/commands.py", line 92, in list_commands
    plugins = sorted(self._plugin_lookup)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/commands.py", line 76, in _plugin_lookup
    import q2cli.core.cache
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 285, in <module>
    CACHE = DeploymentCache()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 205, in _cache_current_state
    state = self._get_current_state()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/core/cache.py", line 253, in _get_current_state
    plugin_manager = q2cli.util.get_plugin_manager()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2cli/util.py", line 236, in get_plugin_manager
    return qiime2.sdk.PluginManager()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 67, in __new__
    self._init(add_plugins=add_plugins)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/qiime2/sdk/plugin_manager.py", line 105, in _init
    plugin = entry_point.load()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2465, in load
    return self.resolve()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2471, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2_fmt/__init__.py", line 10, in <module>
    from ._format import (NDJSONFileFormat, DataResourceSchemaFileFormat,
  File "/opt/homebrew/Caskroom/miniforge/base/envs/q2-fmt-2022.2/lib/python3.8/site-packages/q2_fmt/_format.py", line 11, in <module>
    from frictionless import validate
ModuleNotFoundError: No module named 'frictionless'
```

**Steps to reproduce the behavior**
1. Build new qiime2-2022.2 environment; activate
2. Install from github using git+https://github.com/qiime2/q2-fmt
3. Run `qiime dev refresh-cache`
4. See error. 

**Computation Environment**
- OS: Mac OSX Monterey on M1 machine
- QIIME 2 2022.2 (I think base version)

**Comments**
This seems like it's probably a documentation problem (is `frictionless` a package I should have installed?) which is hopefully a quick fix. I didn't want to dig into the continuous integration commands, which might explain the issue

**Comment by lizgehret** [comment]
Thanks for catching this @jwdebelius - frictionless should be installed prior to installing q2-FMT. Our REAME has been updated accordingly. Please let us know if you run into any further issues!

**Comment by thermokarst** [comment]
@lizgehret - is there any reason why we aren't publishing the conda packages for this plugin? All we need to do is add a Library token to this repo's Secrets and the built packages will be published for you.

cc @ebolyen

**Comment by ebolyen** [comment]
The goal was to not have it in the core-distribution right away (or potentially ever). And I've been hilariously slow at creating the "community" distro.

**Comment by ebolyen** [comment]
stated differently, the speed bumps are on purpose at the moment

**Comment by thermokarst** [comment]
Publishing to packages.qiime2.org is orthogonal to the core distro (or community distro) - you get the best of both world. Just include the relevant channel in the install command and there yah go!

**Comment by ebolyen** [comment]
Thanks @lizgehret for the intial work (I was the one who suggested keeping the pip install) and thanks @thermokarst for pointing out the nicer approach. I've updated the instructions to create an individualized environment (which matches what our CI does, so should be a pretty solid approach):

https://github.com/qiime2/q2-fmt#installation

**Comment by lizgehret** [comment]
Thanks @ebolyen, this is great!

**Comment by thermokarst** [comment]
Thanks for tweaking that @ebolyen, I'm glad that Library et al was able to be helpful here!
